name: Publish Packages
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          pip install setuptools wheel twine
      - name: Build os_runner package
        run: |
          python os_runner/setup.py sdist bdist_wheel
      - name: Publish package
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          TWINE_REPOSITORY_URL: https://maven.pkg.github.com/${{ github.repository }}
        run: |
          twine upload --repository-url $TWINE_REPOSITORY_URL dist/*

