name: Publish 'pg_provisioner_cli' Package (PyPI & GitHub)
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install setuptools wheel twine build
          pip install -r requirements.txt
      - name: Build and Publish 'pg_provisioner_cli' package to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          cd pg_provisioner_cli
          python -m build
          twine upload dist/* --verbose
      - name: Create GitHub Release for 'pg_provisioner_cli' package
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pg_provisioner_cli/dist/*.whl
            pg_provisioner_cli/dist/*.tar.gz
          tag_name: v0.0.1
          name: Release v0.0.1
          body: "The official release of the pg_provisioner_cli_draghici_andrei package."
