name: Publish 'django_rest_api' Package (PyPI & GitHub)
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install setuptools wheel twine build
          pip install -r requirements.txt
      - name: Build 'django_rest_api' package
        run: |
          cd django_rest_api
          python -m build
      - name: Create GitHub Release for 'django_rest_api' package
        uses: softprops/action-gh-release@v2
        with:
          files: |
            django_rest_api/dist/*.whl
            django_rest_api/dist/*.tar.gz
          tag_name: django_rest_api-v0.0.1
          name: Release of 'django_rest_api' v0.0.1
          body: "The official release of the django_rest_api_draghici_andrei package."
#      - name: Build and Publish 'django_rest_api' package to PyPi
#        env:
#          TWINE_USERNAME: __token__
#          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
#        run: |
#          cd django_rest_api
#          python -m build
#          twine upload dist/* --verbose

