name: Test
on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Perform pylint test
        run: |
          pylint os_runner/* --disable="W0718,C0103,C0114"
      - name: Perform flake8 test
        run: | 
          flake8 ./ --ignore=F401
      - name: Perform pytest tests
        run: |
          pytest os_runner_tester.py
        
      
